### ISSUE TITLE
controller exits on `Certificate` with generated name

### ISSUE THREAD

**Issue by mamachanko** [carvel-dev/secretgen-controller#84]
**What steps did you take:**
Apply:
```yaml
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  generateName: root-ca-cert-
  namespace: default
spec:
  isCA: true
```

**What happened:**
The secretgen-controller deployment dies:
```
secretgen-controller-78f5844ddb-fvn26 secretgen-controller E0706 13:07:02.746908       1 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller goroutine 387 [running]:
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/runtime.logPanic({0x131cda0, 0x164d9d0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0x99
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000289000})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x75
secretgen-controller-78f5844ddb-fvn26 secretgen-controller panic({0x131cda0, 0x164d9d0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      runtime/panic.go:1038 +0x215
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.GenerateInputs.Add({{0x13f7240, 0xc00049ca80}}, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/generate_inputs.go:23 +0x65
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).createSecret(0xc000776a50, {0x16799b8, 0xc00089a2a0}, {{0x0, 0x0}, {0x14a0bf4, 0x9}, {0x0, 0x0, 0x0}, ...}, ...)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:119 +0x45e
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).reconcile(0xc000776a50, {0x16799b8, 0xc00089a2a0}, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:79 +0x29d
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).Reconcile(0xc000776a50, {0x16799b8, 0xc00089a2a0}, {{{0xc00064f0e0, 0x138c9c0}, {0xc00064f0d0, 0xc000812340}}})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:70 +0x395
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00076f040, {0x1679910, 0xc0004ac4c0}, {0x1368e00, 0xc000289000})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x303
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00076f040, {0x1679910, 0xc0004ac4c0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1({0x1679910, 0xc0004ac4c0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x46
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x25
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fa4be29dcf8)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x67
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x16542e0, 0xc00089a120}, 0x1, 0xc0000af4a0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xb6
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2, 0x3b9aca00, 0x0, 0x80, 0x1000000020002)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x89
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1679910, 0xc0004ac4c0}, 0xc00057a0e0, 0x0, 0x0, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x99
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x1679910, 0xc0004ac4c0}, 0xc000614c60, 0xc00014ef68)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x2b
secretgen-controller-78f5844ddb-fvn26 secretgen-controller created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4b0
secretgen-controller-78f5844ddb-fvn26 secretgen-controller panic: assignment to entry in nil map [recovered]
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      panic: assignment to entry in nil map
secretgen-controller-78f5844ddb-fvn26 secretgen-controller
secretgen-controller-78f5844ddb-fvn26 secretgen-controller goroutine 387 [running]:
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000289000})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0xd8
secretgen-controller-78f5844ddb-fvn26 secretgen-controller panic({0x131cda0, 0x164d9d0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      runtime/panic.go:1038 +0x215
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.GenerateInputs.Add({{0x13f7240, 0xc00049ca80}}, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/generate_inputs.go:23 +0x65
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).createSecret(0xc000776a50, {0x16799b8, 0xc00089a2a0}, {{0x0, 0x0}, {0x14a0bf4, 0x9}, {0x0, 0x0, 0x0}, ...}, ...)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:119 +0x45e
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).reconcile(0xc000776a50, {0x16799b8, 0xc00089a2a0}, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:79 +0x29d
secretgen-controller-78f5844ddb-fvn26 secretgen-controller github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator.(*CertificateReconciler).Reconcile(0xc000776a50, {0x16799b8, 0xc00089a2a0}, {{{0xc00064f0e0, 0x138c9c0}, {0xc00064f0d0, 0xc000812340}}})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      github.com/vmware-tanzu/carvel-secretgen-controller/pkg/generator/certificate_reconciler.go:70 +0x395
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00076f040, {0x1679910, 0xc0004ac4c0}, {0x1368e00, 0xc000289000})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x303
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00076f040, {0x1679910, 0xc0004ac4c0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
secretgen-controller-78f5844ddb-fvn26 secretgen-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1({0x1679910, 0xc0004ac4c0})
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x46
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x25
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fa4be29dcf8)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x67
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x16542e0, 0xc00089a120}, 0x1, 0xc0000af4a0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xb6
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2, 0x3b9aca00, 0x0, 0x80, 0x1000000020002)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x89
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1679910, 0xc0004ac4c0}, 0xc00057a0e0, 0x0, 0x0, 0x0)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x99
secretgen-controller-78f5844ddb-fvn26 secretgen-controller k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x1679910, 0xc0004ac4c0}, 0xc000614c60, 0xc00014ef68)
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x2b
secretgen-controller-78f5844ddb-fvn26 secretgen-controller created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
secretgen-controller-78f5844ddb-fvn26 secretgen-controller      sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4b0
- secretgen-controller-78f5844ddb-fvn26 › secretgen-controller
```

**What did you expect:**
[A description of what was expected]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- secretgen-controller version (execute `kubectl get deployment -n secretgen-controller secretgen-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
```
kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: v0.8.0_vmware.1
            url: projects-stg.registry.vmware.com/tkg/secretgen-controller:v0.8.0_vmware.1
        - preresolved:
            url: registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:bda67d55ade826092884f49243a797e1e2a946ddbc056b37de7b8a8dedce729a
        url: registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:bda67d55ade826092884f49243a797e1e2a946ddbc056b37de7b8a8dedce729a
    secretgen-controller.carvel.dev/version: v0.8.0
```

- Kubernetes version (use `kubectl version`)
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-24T22:06:50Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment]
Thanks @mamachanko for filing this bug!  We were able to reproduce. 


 notes for fixing: it looks like https://github.com/vmware-tanzu/carvel-secretgen-controller/blob/develop/pkg/generator/generate_inputs.go#L18
is getting a nil map and then crashing - one fix would be to fail more gracefully on nil input but whoever picks up the issue should probably look into root cause.

**Comment by vicmarbev** [comment]
Hi! I've created a pull request to fix this. If I'm not mistaken, the problem resides in the fact that if the certificate yaml does not contain annotations, the map object that [GenerateInputs.Add](https://github.com/vmware-tanzu/carvel-secretgen-controller/blob/bd11288766128351219700fcc2fa7cc3dd6ebe4f/pkg/generator/generate_inputs.go#L18-L24) receives is empty. Does this look good to you?
